# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tcn_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 718)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.console_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.console_1.setGeometry(QtCore.QRect(500, 120, 351, 521))
        self.console_1.setObjectName("console_1")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(10, 0, 241, 61))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(20)
        self.Title.setFont(font)
        self.Title.setTextFormat(QtCore.Qt.PlainText)
        self.Title.setScaledContents(False)
        self.Title.setObjectName("Title")
        self.EmergencyStopBtn = QtWidgets.QPushButton(self.centralwidget)
        self.EmergencyStopBtn.setGeometry(QtCore.QRect(770, 0, 261, 111))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.EmergencyStopBtn.setFont(font)
        self.EmergencyStopBtn.setMouseTracking(False)
        self.EmergencyStopBtn.setAutoFillBackground(False)
        self.EmergencyStopBtn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.011, stop:1 rgba(255, 0, 0, 255));")
        self.EmergencyStopBtn.setObjectName("EmergencyStopBtn")
        self.BridgeConnectionView = QtWidgets.QGraphicsView(self.centralwidget)
        self.BridgeConnectionView.setGeometry(QtCore.QRect(250, 80, 31, 31))
        self.BridgeConnectionView.setStyleSheet("background-color: rgb(255, 3, 3);")
        self.BridgeConnectionView.setObjectName("BridgeConnectionView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 171, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 171, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.LidarConnectionView = QtWidgets.QGraphicsView(self.centralwidget)
        self.LidarConnectionView.setGeometry(QtCore.QRect(250, 120, 31, 31))
        self.LidarConnectionView.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.LidarConnectionView.setObjectName("LidarConnectionView")
        self.VisionView = QtWidgets.QGraphicsView(self.centralwidget)
        self.VisionView.setGeometry(QtCore.QRect(250, 160, 31, 31))
        self.VisionView.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.VisionView.setObjectName("VisionView")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 171, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.MotorView = QtWidgets.QGraphicsView(self.centralwidget)
        self.MotorView.setGeometry(QtCore.QRect(250, 200, 31, 31))
        self.MotorView.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.MotorView.setObjectName("MotorView")
        self.KeyboardControlBtn = QtWidgets.QPushButton(self.centralwidget)
        self.KeyboardControlBtn.setGeometry(QtCore.QRect(20, 290, 201, 71))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.KeyboardControlBtn.setFont(font)
        self.KeyboardControlBtn.setObjectName("KeyboardControlBtn")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 211, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.AlgorithmView = QtWidgets.QGraphicsView(self.centralwidget)
        self.AlgorithmView.setGeometry(QtCore.QRect(250, 240, 31, 31))
        self.AlgorithmView.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.AlgorithmView.setObjectName("AlgorithmView")
        self.BuildMapBtn = QtWidgets.QPushButton(self.centralwidget)
        self.BuildMapBtn.setGeometry(QtCore.QRect(20, 370, 201, 71))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.BuildMapBtn.setFont(font)
        self.BuildMapBtn.setObjectName("BuildMapBtn")
        self.GetLidarDataBtn = QtWidgets.QPushButton(self.centralwidget)
        self.GetLidarDataBtn.setGeometry(QtCore.QRect(20, 450, 201, 71))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.GetLidarDataBtn.setFont(font)
        self.GetLidarDataBtn.setObjectName("GetLidarDataBtn")
        self.LidarOnOffBtn = QtWidgets.QPushButton(self.centralwidget)
        self.LidarOnOffBtn.setGeometry(QtCore.QRect(860, 190, 171, 61))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(10)
        self.LidarOnOffBtn.setFont(font)
        self.LidarOnOffBtn.setObjectName("LidarOnOffBtn")
        self.BridgeOnOffBtn = QtWidgets.QPushButton(self.centralwidget)
        self.BridgeOnOffBtn.setGeometry(QtCore.QRect(860, 120, 171, 61))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(10)
        self.BridgeOnOffBtn.setFont(font)
        self.BridgeOnOffBtn.setObjectName("BridgeOnOffBtn")
        self.VisionOnOffBtn = QtWidgets.QPushButton(self.centralwidget)
        self.VisionOnOffBtn.setGeometry(QtCore.QRect(860, 260, 171, 61))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(10)
        self.VisionOnOffBtn.setFont(font)
        self.VisionOnOffBtn.setObjectName("VisionOnOffBtn")
        self.MotorOnOffBtn = QtWidgets.QPushButton(self.centralwidget)
        self.MotorOnOffBtn.setGeometry(QtCore.QRect(860, 330, 171, 61))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(10)
        self.MotorOnOffBtn.setFont(font)
        self.MotorOnOffBtn.setObjectName("MotorOnOffBtn")
        self.AlgorithmOnOffBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AlgorithmOnOffBtn.setGeometry(QtCore.QRect(860, 400, 171, 61))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(10)
        self.AlgorithmOnOffBtn.setFont(font)
        self.AlgorithmOnOffBtn.setObjectName("AlgorithmOnOffBtn")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(290, 380, 51, 21))
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 380, 58, 15))
        self.label.setObjectName("label")
        self.WayPointModeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.WayPointModeBtn.setGeometry(QtCore.QRect(20, 530, 201, 71))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.WayPointModeBtn.setFont(font)
        self.WayPointModeBtn.setObjectName("WayPointModeBtn")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 10, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(260, 530, 58, 15))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 10, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(500, 10, 261, 101))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(36)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1040, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "TCN HMI"))
        self.EmergencyStopBtn.setText(_translate("MainWindow", "Emergency Stop"))
        self.label_2.setText(_translate("MainWindow", "Bridge Connection"))
        self.label_3.setText(_translate("MainWindow", "LiDAR Connection"))
        self.label_4.setText(_translate("MainWindow", "Vision Connection"))
        self.label_5.setText(_translate("MainWindow", "Motor Connection"))
        self.KeyboardControlBtn.setText(_translate("MainWindow", "Xbox control"))
        self.label_6.setText(_translate("MainWindow", "Algorithm Connection"))
        self.BuildMapBtn.setText(_translate("MainWindow", "Build map"))
        self.GetLidarDataBtn.setText(_translate("MainWindow", "Get LiDAR data"))
        self.LidarOnOffBtn.setText(_translate("MainWindow", "LiDAR On/Off"))
        self.BridgeOnOffBtn.setText(_translate("MainWindow", "Bridge On/Off"))
        self.VisionOnOffBtn.setText(_translate("MainWindow", "Vision On/Off"))
        self.MotorOnOffBtn.setText(_translate("MainWindow", "STM32 On/Off"))
        self.AlgorithmOnOffBtn.setText(_translate("MainWindow", "Algorithm On/Off"))
        self.label.setText(_translate("MainWindow", "Map ID :"))
        self.WayPointModeBtn.setText(_translate("MainWindow", "WayPoint Mode"))
        self.pushButton.setText(_translate("MainWindow", "LED Yellow"))
        self.pushButton_2.setText(_translate("MainWindow", "LED Red"))
        self.label_8.setText(_translate("MainWindow", "Alarm"))

